### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by GenuineHili** [Redherring32/TinyTendo#3]
So I assembled the motherboard, charge boost pcb and cart slot pcb and gave it a try but I always get a white screen when I turn it on.
I tested the cartridge with the cart test, so I know the cartridge is working. Is the audio pcb and button pcb mandatory for the NES to boot?

**Comment by Pearus** [comment]
> So I assembled the motherboard, charge boost pcb and cart slot pcb and gave it a try but I always get a white screen when I turn it on. I tested the cartridge with the cart test, so I know the cartridge is working. Is the audio pcb and button pcb mandatory for the NES to boot?

Audio and button PCBs are not required for booting. If you're getting a white screen, double check the connections on the CPU. If you have the board to test full sized games, that's another good thing to try to confirm if it's something with the connection to the TinyTendo cartridge slot.

**Comment by GenuineHili** [comment]
![IMG_20240311_132507285](https://github.com/Redherring32/TinyTendo/assets/147345143/8b41c50a-c64d-402c-a06b-0a79d4b32b41)
It's working now. I resoldered the 80-pin connector on the cart slot PCB and now it's working. Thank you for your advice.

**Comment by Pearus** [comment]
> ![IMG_20240311_132507285](https://private-user-images.githubusercontent.com/147345143/311771046-8b41c50a-c64d-402c-a06b-0a79d4b32b41.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNzM1MTcsIm5iZiI6MTcxMDE3MzIxNywicGF0aCI6Ii8xNDczNDUxNDMvMzExNzcxMDQ2LThiNDFjNTBhLWM2NGQtNDAyYy1hMDZiLTBhNzlkNGIzMmI0MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQxNjA2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzk1MTY4ZjgxODM4YzA2OWZiZGQ4ZDM1YWVhYjM1YmFkZTJkMWQ1N2RkNWUwZTczNjI1NzU3N2NhNmQ5NGZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SpJPRBsqhSk6zpsMnrAw2sL_9syBciMN1SIk3jqhEYA) It's working now. I resoldered the 80-pin connector on the cart slot PCB and now it's working. Thank you for your advice.

Awesome, glad you got it running!
