### ISSUE TITLE
Brightness Mod

### ISSUE THREAD

**Issue by GenuineHili** [Redherring32/TinyTendo#4]
Is it normal that the screen is rather dark compared to when it's not installed, even when the brightness wheel is all the way up?

**Comment by Pearus** [comment]
I experienced the same, the brightness was significantly lower.

You can play around with max brightness by adjusting "15" in the Arduino sketch to values between 0 and 255:
`analogWrite(8, map(pot, 0, 1023, 0, 15));`

I would be careful and start with small increments.

**Comment by GenuineHili** [comment]
Ok I set the value to 100 and now it's nice and bright. Thank you for your help.
